const CULTIVATION_DROP_IDS = [
  'dagger',
  'short_sword',
  'scimitar',
  'bronze_sword',
  'steel_sword',
  'giant_sword',
  'great_sword',
  'hatchet',
  'double_axe',
  'lianyu',
  'bone_wand',
  'magestaff',
  'silver_snake',
  'armor_leather',
  'armor_light',
  'armor_heavy',
  'armor_war',
  'armor_mage',
  'armor_tao',
  'armor_doom',
  'armor_magic',
  'helm_mystic',
  'helm_wizard',
  'helm_war',
  'helm_mage',
  'helm_tao',
  'helm_holy',
  'boots_war',
  'boots_mage',
  'boots_tao',
  'boots_holy',
  'belt_war',
  'belt_mage',
  'belt_tao',
  'belt_holy',
  'ring_platinum',
  'ring_coral',
  'ring_ruby',
  'ring_dodge',
  'ring_tiger',
  'necklace_life',
  'necklace_green',
  'necklace_evil',
  'necklace_tao',
  'bracelet_dragon',
  'bracelet_eye',
  'bracelet_ghost',
  'bracelet_yanluo',
]
const CULTIVATION_DROP_BASE = 0.002
const CULTIVATION_DROP_STEP = 0.002
const makeCultivationDrops = (tier) => CULTIVATION_DROP_IDS.map((id) => ({ id, chance: CULTIVATION_DROP_BASE + CULTIVATION_DROP_STEP * tier }))
const CULTIVATION_DROPS = {
  zhuji: makeCultivationDrops(0),
  lingxu: makeCultivationDrops(1),
  hehe: makeCultivationDrops(2),
  yuanying: makeCultivationDrops(3),
  kongming: makeCultivationDrops(4),
  lvshuang: makeCultivationDrops(5),
  dujie: makeCultivationDrops(6),
  jimie: makeCultivationDrops(7),
  dacheng: makeCultivationDrops(8),
  shangxian: makeCultivationDrops(9),
  zhenxian: makeCultivationDrops(10),
  tianxian: makeCultivationDrops(11),
}

const CULTIVATION_BOSS_DROP_RATES = {
  epic: 0.006,
  legendary: 0.004,
  supreme: 0.001,
  ultimate: 0.0005,
}
const CULTIVATION_BOSS_DROP_ITEMS = {
  epic: [
    'gold_bar',
    'juejudao',
    'wulong',
    'bone_staff',
    'blood_drink',
    'wujigun',
    'longwen',
    'armor_taishan',
    'armor_molong',
    'ring_strength',
    'ring_bone',
    'ring_tao',
    'ring_holy',
    'ring_fashen',
    'ring_tianzun',
    'ring_def',
    'ring_fire',
    'ring_heal',
    'ring_recall',
    'necklace_memory',
    'necklace_soldier',
    'necklace_fashen',
    'necklace_tianzun',
    'necklace_luck',
    'bracelet_soldier',
    'bracelet_fashen',
    'bracelet_tianzun',
  ],
  legendary: [
    'nujian',
    'kaitian',
    'zhentian',
    'xuantian',
    'armor_thunder',
    'armor_flame',
    'armor_glow',
    'helm_sacred',
    'helm_true',
    'helm_wargod',
    'boots_sacred',
    'boots_true',
    'boots_wargod',
    'belt_sacred',
    'belt_true',
    'belt_wargod',
    'ring_wargod',
    'ring_sacred',
    'ring_true',
    'ring_teleport',
    'ring_protect',
    'ring_revival',
    'ring_magic',
    'ring_break',
    'necklace_wargod',
    'necklace_sacred',
    'necklace_true',
    'bracelet_wargod',
    'bracelet_sacred',
    'bracelet_true',
  ],
  supreme: [
    'book_war_earth_spike',
    'book_war_tiangang',
    'book_mage_thunderstorm',
    'book_mage_group_shield',
    'book_tao_white_tiger',
    'book_tao_moon_fairy',
    'sword_rochie',
    'staff_rochie',
    'sword_rochie_tao',
    'armor_rochie_war',
    'armor_rochie_mage',
    'armor_rochie_tao',
    'helm_rochie_war',
    'helm_rochie_mage',
    'helm_rochie_tao',
    'boots_rochie_war',
    'boots_rochie_mage',
    'boots_rochie_tao',
    'belt_rochie_war',
    'belt_rochie_mage',
    'belt_rochie_tao',
    'ring_rochie_war',
    'ring_rochie_mage',
    'ring_rochie_tao',
    'necklace_rochie_war',
    'necklace_rochie_mage',
    'necklace_rochie_tao',
    'bracelet_rochie_war',
    'bracelet_rochie_mage',
    'bracelet_rochie_tao',
    'treasure_taiyi_disc',
    'treasure_zhoutian_jade',
    'treasure_hongmeng_seal',
    'treasure_taichu_scroll',
    'treasure_ziwei_disc',
    'treasure_taixu_script',
  ],
  ultimate: [
    'sword_caiya',
    'staff_caiya',
    'sword_caiya_tao',
    'armor_caiya_war',
    'armor_caiya_mage',
    'armor_caiya_tao',
    'helm_caiya_war',
    'helm_caiya_mage',
    'helm_caiya_tao',
    'boots_caiya_war',
    'boots_caiya_mage',
    'boots_caiya_tao',
    'belt_caiya_war',
    'belt_caiya_mage',
    'belt_caiya_tao',
    'ring_caiya_war',
    'ring_caiya_mage',
    'ring_caiya_tao',
    'necklace_caiya_war',
    'necklace_caiya_mage',
    'necklace_caiya_tao',
    'bracelet_caiya_war',
    'bracelet_caiya_mage',
    'bracelet_caiya_tao',
  ],
}
const CULTIVATION_BOSS_DROP_STEP = 0.1
const makeCultivationBossDrops = (tier) => {
  const multiplier = 1 + CULTIVATION_BOSS_DROP_STEP * tier
  const drops = []
  Object.keys(CULTIVATION_BOSS_DROP_ITEMS).forEach((rarity) => {
    const rate = (CULTIVATION_BOSS_DROP_RATES[rarity] || 0) * multiplier
    CULTIVATION_BOSS_DROP_ITEMS[rarity].forEach((id) => {
      drops.push({ id, chance: rate })
    })
  })
  return drops
}
const CULTIVATION_BOSS_DROPS = {
  zhuji: makeCultivationBossDrops(0),
  lingxu: makeCultivationBossDrops(1),
  hehe: makeCultivationBossDrops(2),
  yuanying: makeCultivationBossDrops(3),
  kongming: makeCultivationBossDrops(4),
  lvshuang: makeCultivationBossDrops(5),
  dujie: makeCultivationBossDrops(6),
  jimie: makeCultivationBossDrops(7),
  dacheng: makeCultivationBossDrops(8),
  shangxian: makeCultivationBossDrops(9),
  zhenxian: makeCultivationBossDrops(10),
  tianxian: makeCultivationBossDrops(11),
}

CULTIVATION_DROPS.shengwen = makeCultivationDrops(12)
CULTIVATION_DROPS.yuanjue = makeCultivationDrops(13)
CULTIVATION_DROPS.pusa = makeCultivationDrops(14)
CULTIVATION_DROPS.fo = makeCultivationDrops(15)
CULTIVATION_BOSS_DROPS.shengwen = makeCultivationBossDrops(12)
CULTIVATION_BOSS_DROPS.yuanjue = makeCultivationBossDrops(13)
CULTIVATION_BOSS_DROPS.pusa = makeCultivationBossDrops(14)
CULTIVATION_BOSS_DROPS.fo = makeCultivationBossDrops(15)


export const MOB_TEMPLATES = {
  // Basic field
  chicken: { id: 'chicken', name: '鸡', level: 1, hp: 20, atk: 2, def: 0, mdef: 0, exp: 8, gold: [1, 5], drops: [{ id: 'potion_small', chance: 0.05 }] },
  deer: { id: 'deer', name: '鹿', level: 2, hp: 30, atk: 4, def: 0, mdef: 0, exp: 12, gold: [2, 8], drops: [{ id: 'potion_small', chance: 0.08 }] },
  sheep: { id: 'sheep', name: '羊', level: 2, hp: 28, atk: 3, def: 0, mdef: 0, exp: 10, gold: [2, 6], drops: [{ id: 'potion_small', chance: 0.06 }] },
  scarecrow: { id: 'scarecrow', name: '稻草人', level: 5, hp: 60, atk: 8, def: 1, mdef: 1, exp: 25, gold: [5, 12], drops: [{ id: 'potion_small', chance: 0.1 }] },
  cat: { id: 'cat', name: '钉耙猫', level: 5, hp: 85, atk: 12, def: 2, mdef: 2, exp: 38, gold: [5, 12], drops: [{ id: 'potion_small', chance: 0.1 }] },
  wolf: { id: 'wolf', name: '狼', level: 4, hp: 80, atk: 10, def: 2, mdef: 2, exp: 40, gold: [4, 12], drops: [{ id: 'potion_small', chance: 0.1 }, { id: 'boots_leather', chance: 0.02 }] },
  half_orc: { id: 'half_orc', name: '半兽人', level: 7, hp: 140, atk: 16, def: 5, mdef: 5, exp: 85, gold: [10, 20], drops: [{ id: 'armor_chain', chance: 0.03 }] },
  half_orc_warrior: { id: 'half_orc_warrior', name: '半兽战士', level: 9, hp: 180, atk: 20, def: 6, mdef: 6, exp: 120, gold: [12, 24], drops: [{ id: 'bronze_sword', chance: 0.03 }] },
  half_orc_elite: { id: 'half_orc_elite', name: '半兽勇士', level: 12, hp: 260, atk: 26, def: 9, mdef: 9, exp: 200, gold: [18, 40], drops: [{ id: 'great_sword', chance: 0.02 }] },
  bee: { id: 'bee', name: '毒蜂', level: 5, hp: 60, atk: 12, def: 1, mdef: 1, exp: 35, gold: [3, 10], drops: [{ id: 'potion_small', chance: 0.1 }] },
  spider: { id: 'spider', name: '蜘蛛', level: 8, hp: 120, atk: 18, def: 4, mdef: 4, exp: 95, gold: [10, 22], drops: [{ id: 'potion_small', chance: 0.1 }] },

  // Snake valley
  red_snake: { id: 'red_snake', name: '红蛇', level: 10, hp: 160, atk: 20, def: 5, mdef: 5, exp: 130, gold: [12, 26], drops: [{ id: 'potion_mid', chance: 0.08 }] },
  tiger_snake: { id: 'tiger_snake', name: '虎蛇', level: 11, hp: 180, atk: 22, def: 6, mdef: 6, exp: 150, gold: [14, 28], drops: [{ id: 'potion_mid', chance: 0.08 }] },
  evil_snake: { id: 'evil_snake', name: '邪恶毒蛇', level: 16, hp: 440, atk: 34, def: 12, mdef: 12, exp: 216, gold: [25, 51], drops: [{ id: 'potion_mid', chance: 0.08 }] },

  // Mine / cave
  skeleton: { id: 'skeleton', name: '骷髅', level: 6, hp: 120, atk: 14, def: 4, mdef: 4, exp: 70, gold: [8, 18], drops: [{ id: 'potion_small', chance: 0.12 }, { id: 'sword_wood', chance: 0.03 }] },
  zombie: { id: 'zombie', name: '僵尸', level: 8, hp: 160, atk: 18, def: 6, mdef: 6, exp: 110, gold: [12, 26], drops: [{ id: 'potion_small', chance: 0.12 }, { id: 'armor_cloth', chance: 0.03 }] },
  elec_zombie: { id: 'elec_zombie', name: '电僵尸', level: 10, hp: 200, atk: 22, def: 7, mdef: 7, exp: 140, gold: [14, 30], drops: [{ id: 'potion_mid', chance: 0.1 }] },
  craw_zombie: { id: 'craw_zombie', name: '爬行僵尸', level: 11, hp: 220, atk: 24, def: 8, mdef: 8, exp: 160, gold: [16, 34], drops: [{ id: 'potion_mid', chance: 0.1 }] },
  cave_bat: { id: 'cave_bat', name: '洞蛆', level: 9, hp: 150, atk: 18, def: 5, mdef: 5, exp: 120, gold: [12, 26], drops: [{ id: 'potion_small', chance: 0.12 }] },
  black_worm: { id: 'black_worm', name: '黑色恶蛆', level: 12, hp: 240, atk: 26, def: 9, mdef: 9, exp: 180, gold: [18, 36], drops: [{ id: 'potion_mid', chance: 0.1 }] },
  moth: { id: 'moth', name: '楔蛾', level: 12, hp: 220, atk: 24, def: 8, mdef: 8, exp: 170, gold: [16, 34], drops: [{ id: 'potion_mid', chance: 0.1 }] },

  // Wugong cave
  centipede: { id: 'centipede', name: '蜈蚣', level: 14, hp: 280, atk: 28, def: 10, mdef: 10, exp: 220, gold: [20, 40], drops: [{ id: 'potion_mid', chance: 0.1 }] },
  scorpion: { id: 'scorpion', name: '钳虫', level: 16, hp: 340, atk: 32, def: 12, mdef: 12, exp: 260, gold: [22, 46], drops: [{ id: 'potion_mid', chance: 0.12 }] },
  ghoul: { id: 'ghoul', name: '邪恶钳虫', level: 20, hp: 520, atk: 40, def: 16, mdef: 16, exp: 420, gold: [40, 80], drops: [{ id: 'moonblade', chance: 0.03 }, { id: 'armor_chain', chance: 0.05 }, { id: 'book_war_attack', chance: 0.02 }, { id: 'book_mage_resist', chance: 0.02 }, { id: 'book_tao_poison', chance: 0.02 }] },
  bug_queen: { id: 'bug_queen', name: '触龙神', level: 24, hp: 1200, atk: 56, def: 22, mdef: 22, exp: 900, gold: [120, 220], respawnMs: 5 * 60 * 1000, drops: [{ id: 'necklace_green', chance: 0.08 }, { id: 'ring_tiger', chance: 0.08 }, { id: 'book_war_assassinate', chance: 0.03 }, { id: 'book_mage_inferno', chance: 0.03 }, { id: 'book_tao_soul', chance: 0.03 }] },

  // Stone tomb
  pig_red: { id: 'pig_red', name: '红野猪', level: 18, hp: 420, atk: 34, def: 14, mdef: 14, exp: 320, gold: [26, 52], drops: [{ id: 'potion_mid', chance: 0.12 }] },
  pig_black: { id: 'pig_black', name: '黑野猪', level: 20, hp: 480, atk: 38, def: 16, mdef: 16, exp: 360, gold: [30, 60], drops: [{ id: 'potion_mid', chance: 0.12 }] },
  pig_white: { id: 'pig_white', name: '白野猪', level: 21, hp: 627, atk: 43, def: 17, mdef: 17, exp: 387, gold: [36, 72], drops: [{ id: 'potion_mid', chance: 0.12 }] },

  // Woma
  woma_guard: { id: 'woma_guard', name: '沃玛卫士', level: 22, hp: 620, atk: 48, def: 22, mdef: 22, exp: 520, gold: [60, 120], drops: [{ id: 'necklace_life', chance: 0.02 }, { id: 'ring_ruby', chance: 0.02 }] },
  woma_warrior: { id: 'woma_warrior', name: '沃玛战士', level: 24, hp: 720, atk: 54, def: 24, mdef: 24, exp: 580, gold: [70, 140], drops: [{ id: 'ring_ruby', chance: 0.02 }] },
  woma_mage: { id: 'woma_mage', name: '沃玛战将', level: 25, hp: 760, atk: 56, def: 24, mdef: 24, exp: 620, gold: [80, 150], drops: [{ id: 'necklace_life', chance: 0.03 }] },
  woma_leader: { id: 'woma_leader', name: '沃玛教主', level: 28, hp: 1950, atk: 91, def: 39, mdef: 39, exp: 1560, gold: [260, 520], respawnMs: 5 * 60 * 1000, drops: [
    { id: 'necklace_life', chance: 0.12 },
    { id: 'ring_ruby', chance: 0.1 },
    { id: 'magestaff', chance: 0.05 },
    { id: 'silver_snake', chance: 0.05 },
    { id: 'woma_horn', chance: 0.2 },
    { id: 'book_war_halfmoon', chance: 0.04 },
    { id: 'book_mage_explode', chance: 0.04 },
    { id: 'book_tao_invis', chance: 0.04 }
  ] },

  // Zuma
  zuma_archer: { id: 'zuma_archer', name: '祖玛弓箭手', level: 28, hp: 820, atk: 64, def: 28, mdef: 28, exp: 680, gold: [90, 180], drops: [{ id: 'ring_tiger', chance: 0.04 }] },
  zuma_guard: { id: 'zuma_guard', name: '祖玛卫士', level: 30, hp: 960, atk: 70, def: 32, mdef: 32, exp: 760, gold: [100, 200], drops: [{ id: 'necklace_green', chance: 0.04 }] },
  zuma_statue: { id: 'zuma_statue', name: '祖玛雕像', level: 31, hp: 980, atk: 72, def: 33, mdef: 33, exp: 780, gold: [110, 210], drops: [{ id: 'necklace_green', chance: 0.05 }, { id: 'ring_tiger', chance: 0.05 }] },
  zuma_leader: { id: 'zuma_leader', name: '祖玛教主', level: 35, hp: 2860, atk: 117, def: 52, mdef: 52, exp: 2340, gold: [390, 650], respawnMs: 5 * 60 * 1000, drops: [
    { id: 'necklace_green', chance: 0.12 },
    { id: 'ring_tiger', chance: 0.12 },
    { id: 'bone_staff', chance: 0.05 },
    { id: 'longwen', chance: 0.05 },
    { id: 'lianyu', chance: 0.08 },
    { id: 'gold_bar', chance: 0.08 },
    { id: 'ring_def', chance: 0.008 },
    { id: 'ring_fire', chance: 0.008 },
    { id: 'book_war_fire', chance: 0.04 },
    { id: 'book_mage_lightning', chance: 0.04 },
    { id: 'book_tao_armor', chance: 0.04 }
  ] },

  // Chiyue
  chiyue_spider: { id: 'chiyue_spider', name: '月魔蜘蛛', level: 36, hp: 1200, atk: 86, def: 36, mdef: 36, exp: 900, gold: [120, 220], drops: [{ id: 'ring_strength', chance: 0.04 }] },
  chiyue_flower: { id: 'chiyue_flower', name: '花吻蜘蛛', level: 36, hp: 1200, atk: 84, def: 35, mdef: 35, exp: 900, gold: [120, 220], drops: [{ id: 'ring_bone', chance: 0.04 }] },
  chiyue_guard: { id: 'chiyue_guard', name: '双头金刚', level: 40, hp: 2600, atk: 100, def: 46, mdef: 46, exp: 2200, gold: [300, 500], drops: [
    { id: 'armor_war', chance: 0.08 },
    { id: 'armor_mage', chance: 0.08 },
    { id: 'armor_tao', chance: 0.08 }
  ] },
  chiyue_blood: { id: 'chiyue_blood', name: '双头血魔', level: 40, hp: 2600, atk: 100, def: 46, mdef: 46, exp: 2200, gold: [300, 500], drops: [
    { id: 'ring_holy', chance: 0.06 },
    { id: 'ring_fashen', chance: 0.06 },
    { id: 'ring_tianzun', chance: 0.06 }
  ] },
  chiyue_demon: { id: 'chiyue_demon', name: '赤月恶魔', level: 42, hp: 4160, atk: 143, def: 68, mdef: 68, exp: 3380, gold: [520, 910], respawnMs: 5 * 60 * 1000, drops: [
    { id: 'armor_war', chance: 0.06 },
    { id: 'armor_mage', chance: 0.06 },
    { id: 'armor_tao', chance: 0.06 },
    { id: 'helm_war', chance: 0.02 },
    { id: 'helm_mage', chance: 0.02 },
    { id: 'helm_tao', chance: 0.02 },
    { id: 'boots_holy', chance: 0.02 },
    { id: 'boots_mage', chance: 0.02 },
    { id: 'boots_tao', chance: 0.02 },
    { id: 'belt_holy', chance: 0.02 },
    { id: 'belt_mage', chance: 0.02 },
    { id: 'belt_tao', chance: 0.02 },
    { id: 'ring_holy', chance: 0.06 },
    { id: 'ring_fashen', chance: 0.06 },
    { id: 'ring_tianzun', chance: 0.06 },
    { id: 'necklace_soldier', chance: 0.08 },
    { id: 'necklace_fashen', chance: 0.08 },
    { id: 'necklace_tianzun', chance: 0.08 },
    { id: 'bracelet_soldier', chance: 0.04 },
    { id: 'bracelet_fashen', chance: 0.04 },
    { id: 'bracelet_tianzun', chance: 0.04 },
    { id: 'nujian', chance: 0.02 },
    { id: 'blood_drink', chance: 0.02 },
    { id: 'book_war_savage', chance: 0.03 },
    { id: 'book_mage_flash', chance: 0.03 },
    { id: 'book_tao_group_invis', chance: 0.03 },
    { id: 'book_tao_group_heal', chance: 0.03 }
  ] },

  // Fengmo
  fmg_pig: { id: 'fmg_pig', name: '虹魔猪卫', level: 34, hp: 1500, atk: 80, def: 34, mdef: 34, exp: 1200, gold: [180, 300], drops: [{ id: 'ring_strength', chance: 0.05 }] },
  fmg_scorpion: { id: 'fmg_scorpion', name: '虹魔蝎卫', level: 34, hp: 1500, atk: 80, def: 34, mdef: 34, exp: 1200, gold: [180, 300], drops: [{ id: 'ring_bone', chance: 0.05 }] },
  fmg_demon: { id: 'fmg_demon', name: '虹魔教主', level: 38, hp: 3380, atk: 125, def: 57, mdef: 57, exp: 2600, gold: [338, 546], respawnMs: 5 * 60 * 1000, drops: [
    { id: 'ring_strength', chance: 0.06 },
    { id: 'ring_bone', chance: 0.06 },
    { id: 'ring_tao', chance: 0.06 }
  ] },

  // Baibimu / jungle
  tree_demon: { id: 'tree_demon', name: '千年树妖', level: 32, hp: 1800, atk: 78, def: 38, mdef: 38, exp: 1400, gold: [200, 320], respawnMs: 5 * 60 * 1000, drops: [
    { id: 'necklace_luck', chance: 0.12 },
    { id: 'necklace_green', chance: 0.06 },
    { id: 'ring_tiger', chance: 0.05 },
    { id: 'bracelet_iron', chance: 0.08 },
    { id: 'gold_bar', chance: 0.03 }
  ] },

  // Cangyue island
  bone_soldier: { id: 'bone_soldier', name: '骷髅战士', level: 30, hp: 1000, atk: 70, def: 30, mdef: 30, exp: 820, gold: [100, 200], drops: [{ id: 'ring_tiger', chance: 0.05 }] },
  bone_general: { id: 'bone_general', name: '骷髅将军', level: 34, hp: 1400, atk: 82, def: 36, mdef: 36, exp: 1200, gold: [160, 260], drops: [{ id: 'necklace_green', chance: 0.06 }] },
  huangquan: { id: 'huangquan', name: '黄泉教主', level: 38, hp: 3380, atk: 125, def: 57, mdef: 57, exp: 2600, gold: [338, 546], respawnMs: 5 * 60 * 1000, drops: [{ id: 'ring_holy', chance: 0.04 }, { id: 'ring_fashen', chance: 0.04 }, { id: 'ring_tianzun', chance: 0.04 }, { id: 'book_war_savage', chance: 0.03 }, { id: 'book_mage_flash', chance: 0.03 }, { id: 'book_tao_shield', chance: 0.03 }] },

  // Niumo temple
  nmmob: { id: 'nmmob', name: '牛魔将军', level: 38, hp: 1800, atk: 92, def: 42, mdef: 42, exp: 1600, gold: [200, 360], drops: [{ id: 'ring_strength', chance: 0.06 }] },
  nm_mage: { id: 'nm_mage', name: '牛魔法师', level: 36, hp: 1500, atk: 86, def: 38, mdef: 38, exp: 1400, gold: [180, 320], drops: [{ id: 'ring_bone', chance: 0.06 }] },
  nm_boss: { id: 'nm_boss', name: '牛魔王', level: 45, hp: 5200, atk: 156, def: 78, mdef: 78, exp: 4160, gold: [780, 1300], respawnMs: 5 * 60 * 1000, drops: [
    { id: 'juejudao', chance: 0.04 },
    { id: 'blood_drink', chance: 0.04 },
    { id: 'longwen', chance: 0.04 },
    { id: 'gold_bar', chance: 0.1 },
    { id: 'ring_dodge', chance: 0.008 },
    { id: 'book_mage_thunder', chance: 0.03 },
    { id: 'book_tao_skeleton', chance: 0.03 }
  ] },

  // Molong
  molong_guard: { id: 'molong_guard', name: '魔龙力士', level: 48, hp: 4600, atk: 130, def: 70, mdef: 70, exp: 3600, gold: [800, 1200], drops: [{ id: 'ring_strength', chance: 0.06 }] },
  molong_boss: { id: 'molong_boss', name: '魔龙教主', level: 52, hp: 270000, atk: 180, def: 88, mdef: 88, exp: 4500, gold: [1000, 1600], respawnMs: 1 * 60 * 60 * 1000, specialBoss: true, drops: [
    { id: 'armor_molong', chance: 0.12 },
    { id: 'armor_taishan', chance: 0.06 },
    { id: 'armor_doom', chance: 0.06 },
    { id: 'armor_magic', chance: 0.06 },
    { id: 'wulong', chance: 0.02 },
    { id: 'helm_holy', chance: 0.02 },
    { id: 'helm_mage', chance: 0.02 },
    { id: 'helm_tao', chance: 0.02 },
    { id: 'boots_holy', chance: 0.02 },
    { id: 'boots_mage', chance: 0.02 },
    { id: 'boots_tao', chance: 0.02 },
    { id: 'belt_holy', chance: 0.02 },
    { id: 'belt_mage', chance: 0.02 },
    { id: 'belt_tao', chance: 0.02 },
    { id: 'bracelet_soldier', chance: 0.04 },
    { id: 'bracelet_fashen', chance: 0.04 },
    { id: 'bracelet_tianzun', chance: 0.04 },
    { id: 'armor_thunder', chance: 0.02 },
    { id: 'armor_flame', chance: 0.02 },
    { id: 'armor_glow', chance: 0.02 },
    { id: 'helm_wargod', chance: 0.005 },
    { id: 'helm_sacred', chance: 0.005 },
    { id: 'helm_true', chance: 0.005 },
    { id: 'boots_wargod', chance: 0.005 },
    { id: 'boots_sacred', chance: 0.005 },
    { id: 'boots_true', chance: 0.005 },
    { id: 'belt_wargod', chance: 0.005 },
    { id: 'belt_sacred', chance: 0.005 },
    { id: 'belt_true', chance: 0.005 },
    { id: 'ring_wargod', chance: 0.003 },
    { id: 'ring_sacred', chance: 0.003 },
    { id: 'ring_true', chance: 0.003 },
    { id: 'necklace_wargod', chance: 0.003 },
    { id: 'necklace_sacred', chance: 0.003 },
    { id: 'necklace_true', chance: 0.003 },
    { id: 'bracelet_wargod', chance: 0.003 },
    { id: 'bracelet_sacred', chance: 0.003 },
    { id: 'bracelet_true', chance: 0.003 },
    { id: 'ring_magic', chance: 0.005 },
    { id: 'ring_teleport', chance: 0.005 },
    { id: 'ring_protect', chance: 0.005 },
    { id: 'ring_revival', chance: 0.005 },
    { id: 'ring_break', chance: 0.005 },
    { id: 'ring_recall', chance: 0.003 },
    { id: 'book_mage_shield', chance: 0.04 },
    { id: 'book_tao_summon', chance: 0.04 }
  ] }
  ,

  // Dark Bosses
  dark_woma_boss: { id: 'dark_woma_boss', name: '暗之沃玛教主', level: 52, hp: 270000, atk: 180, def: 88, mdef: 88, exp: 4500, gold: [1000, 1600], respawnMs: 1 * 60 * 60 * 1000, specialBoss: true, drops: [
    { id: 'armor_molong', chance: 0.12 },
    { id: 'armor_taishan', chance: 0.06 },
    { id: 'armor_doom', chance: 0.06 },
    { id: 'armor_magic', chance: 0.06 },
    { id: 'wulong', chance: 0.02 },
    { id: 'helm_holy', chance: 0.02 },
    { id: 'helm_mage', chance: 0.02 },
    { id: 'helm_tao', chance: 0.02 },
    { id: 'boots_holy', chance: 0.02 },
    { id: 'boots_mage', chance: 0.02 },
    { id: 'boots_tao', chance: 0.02 },
    { id: 'belt_holy', chance: 0.02 },
    { id: 'belt_mage', chance: 0.02 },
    { id: 'belt_tao', chance: 0.02 },
    { id: 'bracelet_soldier', chance: 0.04 },
    { id: 'bracelet_fashen', chance: 0.04 },
    { id: 'bracelet_tianzun', chance: 0.04 },
    { id: 'armor_thunder', chance: 0.02 },
    { id: 'armor_flame', chance: 0.02 },
    { id: 'armor_glow', chance: 0.02 },
    { id: 'helm_wargod', chance: 0.005 },
    { id: 'helm_sacred', chance: 0.005 },
    { id: 'helm_true', chance: 0.005 },
    { id: 'boots_wargod', chance: 0.005 },
    { id: 'boots_sacred', chance: 0.005 },
    { id: 'boots_true', chance: 0.005 },
    { id: 'belt_wargod', chance: 0.005 },
    { id: 'belt_sacred', chance: 0.005 },
    { id: 'belt_true', chance: 0.005 },
    { id: 'ring_wargod', chance: 0.003 },
    { id: 'ring_sacred', chance: 0.003 },
    { id: 'ring_true', chance: 0.003 },
    { id: 'necklace_wargod', chance: 0.003 },
    { id: 'necklace_sacred', chance: 0.003 },
    { id: 'necklace_true', chance: 0.003 },
    { id: 'bracelet_wargod', chance: 0.003 },
    { id: 'bracelet_sacred', chance: 0.003 },
    { id: 'bracelet_true', chance: 0.003 },
    { id: 'ring_magic', chance: 0.005 },
    { id: 'ring_teleport', chance: 0.005 },
    { id: 'ring_protect', chance: 0.005 },
    { id: 'ring_revival', chance: 0.005 },
    { id: 'ring_break', chance: 0.005 },
    { id: 'ring_recall', chance: 0.003 },
    { id: 'book_mage_shield', chance: 0.04 },
    { id: 'book_tao_summon', chance: 0.04 }
  ] }
  ,

  dark_zuma_boss: { id: 'dark_zuma_boss', name: '暗之祖玛教主', level: 52, hp: 270000, atk: 180, def: 88, mdef: 88, exp: 4500, gold: [1000, 1600], respawnMs: 1 * 60 * 60 * 1000, specialBoss: true, drops: [
    { id: 'armor_molong', chance: 0.12 },
    { id: 'armor_taishan', chance: 0.06 },
    { id: 'armor_doom', chance: 0.06 },
    { id: 'armor_magic', chance: 0.06 },
    { id: 'wulong', chance: 0.02 },
    { id: 'helm_holy', chance: 0.02 },
    { id: 'helm_mage', chance: 0.02 },
    { id: 'helm_tao', chance: 0.02 },
    { id: 'boots_holy', chance: 0.02 },
    { id: 'boots_mage', chance: 0.02 },
    { id: 'boots_tao', chance: 0.02 },
    { id: 'belt_holy', chance: 0.02 },
    { id: 'belt_mage', chance: 0.02 },
    { id: 'belt_tao', chance: 0.02 },
    { id: 'bracelet_soldier', chance: 0.04 },
    { id: 'bracelet_fashen', chance: 0.04 },
    { id: 'bracelet_tianzun', chance: 0.04 },
    { id: 'armor_thunder', chance: 0.02 },
    { id: 'armor_flame', chance: 0.02 },
    { id: 'armor_glow', chance: 0.02 },
    { id: 'helm_wargod', chance: 0.005 },
    { id: 'helm_sacred', chance: 0.005 },
    { id: 'helm_true', chance: 0.005 },
    { id: 'boots_wargod', chance: 0.005 },
    { id: 'boots_sacred', chance: 0.005 },
    { id: 'boots_true', chance: 0.005 },
    { id: 'belt_wargod', chance: 0.005 },
    { id: 'belt_sacred', chance: 0.005 },
    { id: 'belt_true', chance: 0.005 },
    { id: 'ring_wargod', chance: 0.003 },
    { id: 'ring_sacred', chance: 0.003 },
    { id: 'ring_true', chance: 0.003 },
    { id: 'necklace_wargod', chance: 0.003 },
    { id: 'necklace_sacred', chance: 0.003 },
    { id: 'necklace_true', chance: 0.003 },
    { id: 'bracelet_wargod', chance: 0.003 },
    { id: 'bracelet_sacred', chance: 0.003 },
    { id: 'bracelet_true', chance: 0.003 },
    { id: 'ring_magic', chance: 0.005 },
    { id: 'ring_teleport', chance: 0.005 },
    { id: 'ring_protect', chance: 0.005 },
    { id: 'ring_revival', chance: 0.005 },
    { id: 'ring_break', chance: 0.005 },
    { id: 'ring_recall', chance: 0.003 },
    { id: 'book_mage_shield', chance: 0.04 },
    { id: 'book_tao_summon', chance: 0.04 }
  ] }
  ,

  dark_hongmo_boss: { id: 'dark_hongmo_boss', name: '暗之虹魔教主', level: 52, hp: 270000, atk: 180, def: 88, mdef: 88, exp: 4500, gold: [1000, 1600], respawnMs: 1 * 60 * 60 * 1000, specialBoss: true, drops: [
    { id: 'armor_molong', chance: 0.12 },
    { id: 'armor_taishan', chance: 0.06 },
    { id: 'armor_doom', chance: 0.06 },
    { id: 'armor_magic', chance: 0.06 },
    { id: 'wulong', chance: 0.02 },
    { id: 'helm_holy', chance: 0.02 },
    { id: 'helm_mage', chance: 0.02 },
    { id: 'helm_tao', chance: 0.02 },
    { id: 'boots_holy', chance: 0.02 },
    { id: 'boots_mage', chance: 0.02 },
    { id: 'boots_tao', chance: 0.02 },
    { id: 'belt_holy', chance: 0.02 },
    { id: 'belt_mage', chance: 0.02 },
    { id: 'belt_tao', chance: 0.02 },
    { id: 'bracelet_soldier', chance: 0.04 },
    { id: 'bracelet_fashen', chance: 0.04 },
    { id: 'bracelet_tianzun', chance: 0.04 },
    { id: 'armor_thunder', chance: 0.02 },
    { id: 'armor_flame', chance: 0.02 },
    { id: 'armor_glow', chance: 0.02 },
    { id: 'helm_wargod', chance: 0.005 },
    { id: 'helm_sacred', chance: 0.005 },
    { id: 'helm_true', chance: 0.005 },
    { id: 'boots_wargod', chance: 0.005 },
    { id: 'boots_sacred', chance: 0.005 },
    { id: 'boots_true', chance: 0.005 },
    { id: 'belt_wargod', chance: 0.005 },
    { id: 'belt_sacred', chance: 0.005 },
    { id: 'belt_true', chance: 0.005 },
    { id: 'ring_wargod', chance: 0.003 },
    { id: 'ring_sacred', chance: 0.003 },
    { id: 'ring_true', chance: 0.003 },
    { id: 'necklace_wargod', chance: 0.003 },
    { id: 'necklace_sacred', chance: 0.003 },
    { id: 'necklace_true', chance: 0.003 },
    { id: 'bracelet_wargod', chance: 0.003 },
    { id: 'bracelet_sacred', chance: 0.003 },
    { id: 'bracelet_true', chance: 0.003 },
    { id: 'ring_magic', chance: 0.005 },
    { id: 'ring_teleport', chance: 0.005 },
    { id: 'ring_protect', chance: 0.005 },
    { id: 'ring_revival', chance: 0.005 },
    { id: 'ring_break', chance: 0.005 },
    { id: 'ring_recall', chance: 0.003 },
    { id: 'book_mage_shield', chance: 0.04 },
    { id: 'book_tao_summon', chance: 0.04 }
  ] }
  ,

  dark_huangquan_boss: { id: 'dark_huangquan_boss', name: '暗之黄泉教主', level: 52, hp: 270000, atk: 180, def: 88, mdef: 88, exp: 4500, gold: [1000, 1600], respawnMs: 1 * 60 * 60 * 1000, specialBoss: true, drops: [
    { id: 'armor_molong', chance: 0.12 },
    { id: 'armor_taishan', chance: 0.06 },
    { id: 'armor_doom', chance: 0.06 },
    { id: 'armor_magic', chance: 0.06 },
    { id: 'wulong', chance: 0.02 },
    { id: 'helm_holy', chance: 0.02 },
    { id: 'helm_mage', chance: 0.02 },
    { id: 'helm_tao', chance: 0.02 },
    { id: 'boots_holy', chance: 0.02 },
    { id: 'boots_mage', chance: 0.02 },
    { id: 'boots_tao', chance: 0.02 },
    { id: 'belt_holy', chance: 0.02 },
    { id: 'belt_mage', chance: 0.02 },
    { id: 'belt_tao', chance: 0.02 },
    { id: 'bracelet_soldier', chance: 0.04 },
    { id: 'bracelet_fashen', chance: 0.04 },
    { id: 'bracelet_tianzun', chance: 0.04 },
    { id: 'armor_thunder', chance: 0.02 },
    { id: 'armor_flame', chance: 0.02 },
    { id: 'armor_glow', chance: 0.02 },
    { id: 'helm_wargod', chance: 0.005 },
    { id: 'helm_sacred', chance: 0.005 },
    { id: 'helm_true', chance: 0.005 },
    { id: 'boots_wargod', chance: 0.005 },
    { id: 'boots_sacred', chance: 0.005 },
    { id: 'boots_true', chance: 0.005 },
    { id: 'belt_wargod', chance: 0.005 },
    { id: 'belt_sacred', chance: 0.005 },
    { id: 'belt_true', chance: 0.005 },
    { id: 'ring_wargod', chance: 0.003 },
    { id: 'ring_sacred', chance: 0.003 },
    { id: 'ring_true', chance: 0.003 },
    { id: 'necklace_wargod', chance: 0.003 },
    { id: 'necklace_sacred', chance: 0.003 },
    { id: 'necklace_true', chance: 0.003 },
    { id: 'bracelet_wargod', chance: 0.003 },
    { id: 'bracelet_sacred', chance: 0.003 },
    { id: 'bracelet_true', chance: 0.003 },
    { id: 'ring_magic', chance: 0.005 },
    { id: 'ring_teleport', chance: 0.005 },
    { id: 'ring_protect', chance: 0.005 },
    { id: 'ring_revival', chance: 0.005 },
    { id: 'ring_break', chance: 0.005 },
    { id: 'ring_recall', chance: 0.003 },
    { id: 'book_mage_shield', chance: 0.04 },
    { id: 'book_tao_summon', chance: 0.04 }
  ] }
  ,

  dark_doublehead_boss: { id: 'dark_doublehead_boss', name: '暗之双头血魔', level: 52, hp: 270000, atk: 180, def: 88, mdef: 88, exp: 4500, gold: [1000, 1600], respawnMs: 1 * 60 * 60 * 1000, specialBoss: true, drops: [
    { id: 'armor_molong', chance: 0.12 },
    { id: 'armor_taishan', chance: 0.06 },
    { id: 'armor_doom', chance: 0.06 },
    { id: 'armor_magic', chance: 0.06 },
    { id: 'wulong', chance: 0.02 },
    { id: 'helm_holy', chance: 0.02 },
    { id: 'helm_mage', chance: 0.02 },
    { id: 'helm_tao', chance: 0.02 },
    { id: 'boots_holy', chance: 0.02 },
    { id: 'boots_mage', chance: 0.02 },
    { id: 'boots_tao', chance: 0.02 },
    { id: 'belt_holy', chance: 0.02 },
    { id: 'belt_mage', chance: 0.02 },
    { id: 'belt_tao', chance: 0.02 },
    { id: 'bracelet_soldier', chance: 0.04 },
    { id: 'bracelet_fashen', chance: 0.04 },
    { id: 'bracelet_tianzun', chance: 0.04 },
    { id: 'armor_thunder', chance: 0.02 },
    { id: 'armor_flame', chance: 0.02 },
    { id: 'armor_glow', chance: 0.02 },
    { id: 'helm_wargod', chance: 0.005 },
    { id: 'helm_sacred', chance: 0.005 },
    { id: 'helm_true', chance: 0.005 },
    { id: 'boots_wargod', chance: 0.005 },
    { id: 'boots_sacred', chance: 0.005 },
    { id: 'boots_true', chance: 0.005 },
    { id: 'belt_wargod', chance: 0.005 },
    { id: 'belt_sacred', chance: 0.005 },
    { id: 'belt_true', chance: 0.005 },
    { id: 'ring_wargod', chance: 0.003 },
    { id: 'ring_sacred', chance: 0.003 },
    { id: 'ring_true', chance: 0.003 },
    { id: 'necklace_wargod', chance: 0.003 },
    { id: 'necklace_sacred', chance: 0.003 },
    { id: 'necklace_true', chance: 0.003 },
    { id: 'bracelet_wargod', chance: 0.003 },
    { id: 'bracelet_sacred', chance: 0.003 },
    { id: 'bracelet_true', chance: 0.003 },
    { id: 'ring_magic', chance: 0.005 },
    { id: 'ring_teleport', chance: 0.005 },
    { id: 'ring_protect', chance: 0.005 },
    { id: 'ring_revival', chance: 0.005 },
    { id: 'ring_break', chance: 0.005 },
    { id: 'ring_recall', chance: 0.003 },
    { id: 'book_mage_shield', chance: 0.04 },
    { id: 'book_tao_summon', chance: 0.04 }
  ] }
  ,

  dark_skeleton_boss: { id: 'dark_skeleton_boss', name: '暗之骷髅精灵', level: 52, hp: 270000, atk: 180, def: 88, mdef: 88, exp: 4500, gold: [1000, 1600], respawnMs: 1 * 60 * 60 * 1000, specialBoss: true, drops: [
    { id: 'armor_molong', chance: 0.12 },
    { id: 'armor_taishan', chance: 0.06 },
    { id: 'armor_doom', chance: 0.06 },
    { id: 'armor_magic', chance: 0.06 },
    { id: 'wulong', chance: 0.02 },
    { id: 'helm_holy', chance: 0.02 },
    { id: 'helm_mage', chance: 0.02 },
    { id: 'helm_tao', chance: 0.02 },
    { id: 'boots_holy', chance: 0.02 },
    { id: 'boots_mage', chance: 0.02 },
    { id: 'boots_tao', chance: 0.02 },
    { id: 'belt_holy', chance: 0.02 },
    { id: 'belt_mage', chance: 0.02 },
    { id: 'belt_tao', chance: 0.02 },
    { id: 'bracelet_soldier', chance: 0.04 },
    { id: 'bracelet_fashen', chance: 0.04 },
    { id: 'bracelet_tianzun', chance: 0.04 },
    { id: 'armor_thunder', chance: 0.02 },
    { id: 'armor_flame', chance: 0.02 },
    { id: 'armor_glow', chance: 0.02 },
    { id: 'helm_wargod', chance: 0.005 },
    { id: 'helm_sacred', chance: 0.005 },
    { id: 'helm_true', chance: 0.005 },
    { id: 'boots_wargod', chance: 0.005 },
    { id: 'boots_sacred', chance: 0.005 },
    { id: 'boots_true', chance: 0.005 },
    { id: 'belt_wargod', chance: 0.005 },
    { id: 'belt_sacred', chance: 0.005 },
    { id: 'belt_true', chance: 0.005 },
    { id: 'ring_wargod', chance: 0.003 },
    { id: 'ring_sacred', chance: 0.003 },
    { id: 'ring_true', chance: 0.003 },
    { id: 'necklace_wargod', chance: 0.003 },
    { id: 'necklace_sacred', chance: 0.003 },
    { id: 'necklace_true', chance: 0.003 },
    { id: 'bracelet_wargod', chance: 0.003 },
    { id: 'bracelet_sacred', chance: 0.003 },
    { id: 'bracelet_true', chance: 0.003 },
    { id: 'ring_magic', chance: 0.005 },
    { id: 'ring_teleport', chance: 0.005 },
    { id: 'ring_protect', chance: 0.005 },
    { id: 'ring_revival', chance: 0.005 },
    { id: 'ring_break', chance: 0.005 },
    { id: 'ring_recall', chance: 0.003 },
    { id: 'book_mage_shield', chance: 0.04 },
    { id: 'book_tao_summon', chance: 0.04 }
  ] }
  ,

  vip_personal_boss: {
    id: 'vip_personal_boss',
    name: '洛奇',
    level: 58,
    hp: 420000,
    atk: 170,
    def: 180,
    mdef: 180,
    exp: 7800,
    gold: [1500, 2600],
    worldBoss: true,
    specialBoss: true,
    respawnMs: 10 * 60 * 1000,
    drops: [
      { id: 'kaitian', chance: 0.012 },
      { id: 'zhentian', chance: 0.012 },
      { id: 'xuantian', chance: 0.012 },
      { id: 'sword_rochie', chance: 0.006 },
      { id: 'staff_rochie', chance: 0.006 },
      { id: 'sword_rochie_tao', chance: 0.006 },
      { id: 'armor_rochie_war', chance: 0.006 },
      { id: 'armor_rochie_mage', chance: 0.006 },
      { id: 'armor_rochie_tao', chance: 0.006 },
      { id: 'helm_rochie_war', chance: 0.005 },
      { id: 'helm_rochie_mage', chance: 0.005 },
      { id: 'helm_rochie_tao', chance: 0.005 },
      { id: 'boots_rochie_war', chance: 0.005 },
      { id: 'boots_rochie_mage', chance: 0.005 },
      { id: 'boots_rochie_tao', chance: 0.005 },
      { id: 'belt_rochie_war', chance: 0.005 },
      { id: 'belt_rochie_mage', chance: 0.005 },
      { id: 'belt_rochie_tao', chance: 0.005 },
      { id: 'ring_rochie_war', chance: 0.005 },
      { id: 'ring_rochie_mage', chance: 0.005 },
      { id: 'ring_rochie_tao', chance: 0.005 },
      { id: 'necklace_rochie_war', chance: 0.005 },
      { id: 'necklace_rochie_mage', chance: 0.005 },
      { id: 'necklace_rochie_tao', chance: 0.005 },
      { id: 'bracelet_rochie_war', chance: 0.005 },
      { id: 'bracelet_rochie_mage', chance: 0.005 },
      { id: 'bracelet_rochie_tao', chance: 0.005 },
      { id: 'treasure_taiyi_disc', chance: 0.005 },
      { id: 'treasure_zhoutian_jade', chance: 0.005 },
      { id: 'treasure_hongmeng_seal', chance: 0.005 },
      { id: 'treasure_taichu_scroll', chance: 0.005 },
      { id: 'treasure_ziwei_disc', chance: 0.005 },
      { id: 'treasure_taixu_script', chance: 0.005 },
      { id: 'book_war_earth_spike', chance: 0.02 },
      { id: 'book_mage_thunderstorm', chance: 0.02 },
      { id: 'book_tao_white_tiger', chance: 0.02 },
      { id: 'book_war_tiangang', chance: 0.01 },
      { id: 'book_mage_group_shield', chance: 0.01 },
      { id: 'book_tao_moon_fairy', chance: 0.01 },
      { id: 'ring_magic', chance: 0.004 },
      { id: 'ring_teleport', chance: 0.004 },
      { id: 'ring_protect', chance: 0.004 },
      { id: 'ring_revival', chance: 0.004 },
      { id: 'ring_break', chance: 0.004 },
      { id: 'ring_recall', chance: 0.003 }
    ]
  },
  svip_personal_boss: {
    id: 'svip_personal_boss',
    name: '菜芽',
    level: 60,
    hp: 600000,
    atk: 180,
    def: 210,
    mdef: 210,
    exp: 9000,
    gold: [2000, 3200],
    worldBoss: true,
    specialBoss: true,
    allowUltimateDrop: true,
    respawnMs: 10 * 60 * 1000,
    drops: [
      { id: 'kaitian', chance: 0.015 },
      { id: 'zhentian', chance: 0.015 },
      { id: 'xuantian', chance: 0.015 },
      { id: 'sword_rochie', chance: 0.008 },
      { id: 'staff_rochie', chance: 0.008 },
      { id: 'sword_rochie_tao', chance: 0.008 },
      { id: 'armor_rochie_war', chance: 0.008 },
      { id: 'armor_rochie_mage', chance: 0.008 },
      { id: 'armor_rochie_tao', chance: 0.008 },
      { id: 'helm_rochie_war', chance: 0.006 },
      { id: 'helm_rochie_mage', chance: 0.006 },
      { id: 'helm_rochie_tao', chance: 0.006 },
      { id: 'boots_rochie_war', chance: 0.006 },
      { id: 'boots_rochie_mage', chance: 0.006 },
      { id: 'boots_rochie_tao', chance: 0.006 },
      { id: 'belt_rochie_war', chance: 0.006 },
      { id: 'belt_rochie_mage', chance: 0.006 },
      { id: 'belt_rochie_tao', chance: 0.006 },
      { id: 'ring_rochie_war', chance: 0.006 },
      { id: 'ring_rochie_mage', chance: 0.006 },
      { id: 'ring_rochie_tao', chance: 0.006 },
      { id: 'necklace_rochie_war', chance: 0.006 },
      { id: 'necklace_rochie_mage', chance: 0.006 },
      { id: 'necklace_rochie_tao', chance: 0.006 },
      { id: 'bracelet_rochie_war', chance: 0.006 },
      { id: 'bracelet_rochie_mage', chance: 0.006 },
      { id: 'bracelet_rochie_tao', chance: 0.006 },
      { id: 'treasure_taiyi_disc', chance: 0.003 },
      { id: 'treasure_zhoutian_jade', chance: 0.003 },
      { id: 'treasure_hongmeng_seal', chance: 0.003 },
      { id: 'treasure_taichu_scroll', chance: 0.003 },
      { id: 'treasure_ziwei_disc', chance: 0.003 },
      { id: 'treasure_taixu_script', chance: 0.003 },
      { id: 'book_war_earth_spike', chance: 0.03 },
      { id: 'book_mage_thunderstorm', chance: 0.03 },
      { id: 'book_tao_white_tiger', chance: 0.03 },
      { id: 'book_war_tiangang', chance: 0.02 },
      { id: 'book_mage_group_shield', chance: 0.02 },
      { id: 'book_tao_moon_fairy', chance: 0.02 },
      { id: 'sword_caiya', chance: 0.003 },
      { id: 'staff_caiya', chance: 0.003 },
      { id: 'sword_caiya_tao', chance: 0.003 },
      { id: 'armor_caiya_war', chance: 0.003 },
      { id: 'armor_caiya_mage', chance: 0.003 },
      { id: 'armor_caiya_tao', chance: 0.003 },
      { id: 'helm_caiya_war', chance: 0.003 },
      { id: 'helm_caiya_mage', chance: 0.003 },
      { id: 'helm_caiya_tao', chance: 0.003 },
      { id: 'boots_caiya_war', chance: 0.003 },
      { id: 'boots_caiya_mage', chance: 0.003 },
      { id: 'boots_caiya_tao', chance: 0.003 },
      { id: 'belt_caiya_war', chance: 0.003 },
      { id: 'belt_caiya_mage', chance: 0.003 },
      { id: 'belt_caiya_tao', chance: 0.003 },
      { id: 'ring_caiya_war', chance: 0.0025 },
      { id: 'ring_caiya_mage', chance: 0.0025 },
      { id: 'ring_caiya_tao', chance: 0.0025 },
      { id: 'necklace_caiya_war', chance: 0.0025 },
      { id: 'necklace_caiya_mage', chance: 0.0025 },
      { id: 'necklace_caiya_tao', chance: 0.0025 },
      { id: 'bracelet_caiya_war', chance: 0.0025 },
      { id: 'bracelet_caiya_mage', chance: 0.0025 },
      { id: 'bracelet_caiya_tao', chance: 0.0025 }
    ]
  },
  world_boss: {
    id: 'world_boss',
    name: '世界BOSS·炎龙',
    level: 60,
    hp: 600000,
    atk: 180,
    def: 210,
    mdef: 210,
    exp: 9000,
    gold: [2000, 3200],
    worldBoss: true,
    specialBoss: true,
    respawnMs: 1 * 60 * 60 * 1000,
    drops: [
      { id: 'cultivation_rebirth_stone', chance: 0.08 },
      { id: 'kaitian', chance: 0.015 },
      { id: 'zhentian', chance: 0.015 },
      { id: 'xuantian', chance: 0.015 },
      { id: 'sword_rochie', chance: 0.005 },
      { id: 'staff_rochie', chance: 0.005 },
      { id: 'sword_rochie_tao', chance: 0.005 },
      { id: 'armor_rochie_war', chance: 0.005 },
      { id: 'armor_rochie_mage', chance: 0.005 },
      { id: 'armor_rochie_tao', chance: 0.005 },
      { id: 'armor_molong', chance: 0.12 },
      { id: 'armor_taishan', chance: 0.06 },
      { id: 'armor_doom', chance: 0.06 },
      { id: 'armor_magic', chance: 0.06 },
      { id: 'wulong', chance: 0.04 },
      { id: 'nujian', chance: 0.04 },
      { id: 'blood_drink', chance: 0.04 },
      { id: 'helm_rochie_war', chance: 0.005 },
      { id: 'helm_rochie_mage', chance: 0.005 },
      { id: 'helm_rochie_tao', chance: 0.005 },
      { id: 'helm_holy', chance: 0.02 },
      { id: 'helm_mage', chance: 0.02 },
      { id: 'helm_tao', chance: 0.02 },
      { id: 'boots_rochie_war', chance: 0.005 },
      { id: 'boots_rochie_mage', chance: 0.005 },
      { id: 'boots_rochie_tao', chance: 0.005 },
      { id: 'boots_holy', chance: 0.02 },
      { id: 'boots_mage', chance: 0.02 },
      { id: 'boots_tao', chance: 0.02 },
      { id: 'belt_rochie_war', chance: 0.005 },
      { id: 'belt_rochie_mage', chance: 0.005 },
      { id: 'belt_rochie_tao', chance: 0.005 },
      { id: 'belt_holy', chance: 0.02 },
      { id: 'belt_mage', chance: 0.02 },
      { id: 'belt_tao', chance: 0.02 },
      { id: 'ring_rochie_war', chance: 0.005 },
      { id: 'ring_rochie_mage', chance: 0.005 },
      { id: 'ring_rochie_tao', chance: 0.005 },
      { id: 'bracelet_rochie_war', chance: 0.005 },
      { id: 'bracelet_rochie_mage', chance: 0.005 },
      { id: 'bracelet_rochie_tao', chance: 0.005 },
      { id: 'bracelet_caiya_war', chance: 0.002 },
      { id: 'bracelet_caiya_mage', chance: 0.002 },
      { id: 'bracelet_caiya_tao', chance: 0.002 },
      { id: 'necklace_rochie_war', chance: 0.005 },
      { id: 'necklace_rochie_mage', chance: 0.005 },
      { id: 'necklace_rochie_tao', chance: 0.005 },
      { id: 'bracelet_soldier', chance: 0.04 },
      { id: 'bracelet_fashen', chance: 0.04 },
      { id: 'bracelet_tianzun', chance: 0.04 },
      { id: 'armor_thunder', chance: 0.015 },
      { id: 'armor_flame', chance: 0.015 },
      { id: 'armor_glow', chance: 0.015 },
      { id: 'helm_wargod', chance: 0.008 },
      { id: 'helm_sacred', chance: 0.008 },
      { id: 'helm_true', chance: 0.008 },
      { id: 'boots_wargod', chance: 0.008 },
      { id: 'boots_sacred', chance: 0.008 },
      { id: 'boots_true', chance: 0.008 },
      { id: 'belt_wargod', chance: 0.008 },
      { id: 'belt_sacred', chance: 0.008 },
      { id: 'belt_true', chance: 0.008 },
      { id: 'ring_holy', chance: 0.04 },
      { id: 'ring_fashen', chance: 0.04 },
      { id: 'ring_tianzun', chance: 0.04 },
      { id: 'necklace_soldier', chance: 0.04 },
      { id: 'necklace_fashen', chance: 0.04 },
      { id: 'necklace_tianzun', chance: 0.04 },
      { id: 'ring_wargod', chance: 0.005 },
      { id: 'ring_sacred', chance: 0.005 },
      { id: 'ring_true', chance: 0.005 },
      { id: 'necklace_wargod', chance: 0.005 },
      { id: 'necklace_sacred', chance: 0.005 },
      { id: 'necklace_true', chance: 0.005 },
      { id: 'bracelet_wargod', chance: 0.005 },
      { id: 'bracelet_sacred', chance: 0.005 },
      { id: 'bracelet_true', chance: 0.005 },
      { id: 'ring_dodge', chance: 0.015 },
      { id: 'ring_def', chance: 0.015 },
      { id: 'ring_fire', chance: 0.015 },
      { id: 'ring_heal', chance: 0.015 },
      { id: 'ring_magic', chance: 0.015 },
      { id: 'ring_teleport', chance: 0.015 },
      { id: 'ring_protect', chance: 0.015 },
      { id: 'ring_revival', chance: 0.015 },
      { id: 'ring_break', chance: 0.015 },
      { id: 'ring_recall', chance: 0.008 },
      { id: 'scroll_recall', chance: 0.06 },
      { id: 'book_mage_ice', chance: 0.05 },
      { id: 'book_war_earth_spike', chance: 0.03 },
      { id: 'book_mage_thunderstorm', chance: 0.03 },
      { id: 'book_tao_white_tiger', chance: 0.03 },
      { id: 'book_war_tiangang', chance: 0.03 },
      { id: 'book_mage_group_shield', chance: 0.03 },
      { id: 'book_tao_moon_fairy', chance: 0.03 },
      { id: 'treasure_fentian_mark', chance: 0.01 },
      { id: 'treasure_blood_blade', chance: 0.01 },
      { id: 'treasure_chixiao_talisman', chance: 0.01 },
      { id: 'treasure_cangyan_flag', chance: 0.01 },
      { id: 'treasure_fenyu_wheel', chance: 0.01 },
      { id: 'treasure_jiehuo_token', chance: 0.01 },
      { id: 'treasure_xuanwu_core', chance: 0.01 },
      { id: 'treasure_taiyin_mirror', chance: 0.01 },
      { id: 'treasure_guiyuan_bead', chance: 0.01 },
      { id: 'treasure_youluo_lamp', chance: 0.01 },
      { id: 'treasure_shigou_nail', chance: 0.01 },
      { id: 'treasure_shehun_banner', chance: 0.01 },
      { id: 'treasure_shiling_chain', chance: 0.01 },
      { id: 'treasure_duanpo_bell', chance: 0.01 },
      { id: 'treasure_fushen_lu', chance: 0.01 }
    ]
  },
  cross_world_boss: {
    id: 'cross_world_boss',
    name: '跨服BOSS·白虎',
    level: 60,
    hp: 600000,
    atk: 180,
    def: 210,
    mdef: 210,
    exp: 9000,
    gold: [2000, 3200],
    worldBoss: true,
    specialBoss: true,
    respawnMs: 1 * 60 * 60 * 1000,
    drops: [
      { id: 'kaitian', chance: 0.015 },
      { id: 'zhentian', chance: 0.015 },
      { id: 'xuantian', chance: 0.015 },
      { id: 'sword_rochie', chance: 0.005 },
      { id: 'staff_rochie', chance: 0.005 },
      { id: 'sword_rochie_tao', chance: 0.005 },
      { id: 'sword_caiya', chance: 0.0025 },
      { id: 'staff_caiya', chance: 0.0025 },
      { id: 'sword_caiya_tao', chance: 0.0025 },
      { id: 'armor_rochie_war', chance: 0.005 },
      { id: 'armor_rochie_mage', chance: 0.005 },
      { id: 'armor_rochie_tao', chance: 0.005 },
      { id: 'armor_caiya_war', chance: 0.0025 },
      { id: 'armor_caiya_mage', chance: 0.0025 },
      { id: 'armor_caiya_tao', chance: 0.0025 },
      { id: 'armor_molong', chance: 0.12 },
      { id: 'armor_taishan', chance: 0.06 },
      { id: 'armor_doom', chance: 0.06 },
      { id: 'armor_magic', chance: 0.06 },
      { id: 'wulong', chance: 0.04 },
      { id: 'nujian', chance: 0.04 },
      { id: 'blood_drink', chance: 0.04 },
      { id: 'helm_rochie_war', chance: 0.005 },
      { id: 'helm_rochie_mage', chance: 0.005 },
      { id: 'helm_rochie_tao', chance: 0.005 },
      { id: 'helm_caiya_war', chance: 0.0025 },
      { id: 'helm_caiya_mage', chance: 0.0025 },
      { id: 'helm_caiya_tao', chance: 0.0025 },
      { id: 'helm_holy', chance: 0.02 },
      { id: 'helm_mage', chance: 0.02 },
      { id: 'helm_tao', chance: 0.02 },
      { id: 'boots_rochie_war', chance: 0.005 },
      { id: 'boots_rochie_mage', chance: 0.005 },
      { id: 'boots_rochie_tao', chance: 0.005 },
      { id: 'boots_caiya_war', chance: 0.0025 },
      { id: 'boots_caiya_mage', chance: 0.0025 },
      { id: 'boots_caiya_tao', chance: 0.0025 },
      { id: 'boots_holy', chance: 0.02 },
      { id: 'boots_mage', chance: 0.02 },
      { id: 'boots_tao', chance: 0.02 },
      { id: 'belt_rochie_war', chance: 0.005 },
      { id: 'belt_rochie_mage', chance: 0.005 },
      { id: 'belt_rochie_tao', chance: 0.005 },
      { id: 'belt_caiya_war', chance: 0.0025 },
      { id: 'belt_caiya_mage', chance: 0.0025 },
      { id: 'belt_caiya_tao', chance: 0.0025 },
      { id: 'belt_holy', chance: 0.02 },
      { id: 'belt_mage', chance: 0.02 },
      { id: 'belt_tao', chance: 0.02 },
      { id: 'ring_rochie_war', chance: 0.005 },
      { id: 'ring_rochie_mage', chance: 0.005 },
      { id: 'ring_rochie_tao', chance: 0.005 },
      { id: 'ring_caiya_war', chance: 0.0025 },
      { id: 'ring_caiya_mage', chance: 0.0025 },
      { id: 'ring_caiya_tao', chance: 0.0025 },
      { id: 'bracelet_rochie_war', chance: 0.005 },
      { id: 'bracelet_rochie_mage', chance: 0.005 },
      { id: 'bracelet_rochie_tao', chance: 0.005 },
      { id: 'bracelet_caiya_war', chance: 0.0025 },
      { id: 'bracelet_caiya_mage', chance: 0.0025 },
      { id: 'bracelet_caiya_tao', chance: 0.0025 },
      { id: 'necklace_rochie_war', chance: 0.005 },
      { id: 'necklace_rochie_mage', chance: 0.005 },
      { id: 'necklace_rochie_tao', chance: 0.005 },
      { id: 'necklace_caiya_war', chance: 0.0025 },
      { id: 'necklace_caiya_mage', chance: 0.0025 },
      { id: 'necklace_caiya_tao', chance: 0.0025 },
      { id: 'bracelet_soldier', chance: 0.04 },
      { id: 'bracelet_fashen', chance: 0.04 },
      { id: 'bracelet_tianzun', chance: 0.04 },
      { id: 'armor_thunder', chance: 0.015 },
      { id: 'armor_flame', chance: 0.015 },
      { id: 'armor_glow', chance: 0.015 },
      { id: 'helm_wargod', chance: 0.008 },
      { id: 'helm_sacred', chance: 0.008 },
      { id: 'helm_true', chance: 0.008 },
      { id: 'boots_wargod', chance: 0.008 },
      { id: 'boots_sacred', chance: 0.008 },
      { id: 'boots_true', chance: 0.008 },
      { id: 'belt_wargod', chance: 0.008 },
      { id: 'belt_sacred', chance: 0.008 },
      { id: 'belt_true', chance: 0.008 },
      { id: 'ring_holy', chance: 0.04 },
      { id: 'ring_fashen', chance: 0.04 },
      { id: 'ring_tianzun', chance: 0.04 },
      { id: 'necklace_soldier', chance: 0.04 },
      { id: 'necklace_fashen', chance: 0.04 },
      { id: 'necklace_tianzun', chance: 0.04 },
      { id: 'ring_wargod', chance: 0.005 },
      { id: 'ring_sacred', chance: 0.005 },
      { id: 'ring_true', chance: 0.005 },
      { id: 'necklace_wargod', chance: 0.005 },
      { id: 'necklace_sacred', chance: 0.005 },
      { id: 'necklace_true', chance: 0.005 },
      { id: 'bracelet_wargod', chance: 0.005 },
      { id: 'bracelet_sacred', chance: 0.005 },
      { id: 'bracelet_true', chance: 0.005 },
      { id: 'ring_dodge', chance: 0.015 },
      { id: 'ring_def', chance: 0.015 },
      { id: 'ring_fire', chance: 0.015 },
      { id: 'ring_heal', chance: 0.015 },
      { id: 'ring_magic', chance: 0.015 },
      { id: 'ring_teleport', chance: 0.015 },
      { id: 'ring_protect', chance: 0.015 },
      { id: 'ring_revival', chance: 0.015 },
      { id: 'ring_break', chance: 0.015 },
      { id: 'ring_recall', chance: 0.008 },
      { id: 'scroll_recall', chance: 0.06 },
      { id: 'book_mage_ice', chance: 0.05 },
      { id: 'book_war_earth_spike', chance: 0.03 },
      { id: 'book_mage_thunderstorm', chance: 0.03 },
      { id: 'book_tao_white_tiger', chance: 0.03 },
      { id: 'book_war_tiangang', chance: 0.03 },
      { id: 'book_mage_group_shield', chance: 0.03 },
      { id: 'book_tao_moon_fairy', chance: 0.03 },
      { id: 'treasure_fentian_mark', chance: 0.015 },
      { id: 'treasure_blood_blade', chance: 0.015 },
      { id: 'treasure_chixiao_talisman', chance: 0.015 },
      { id: 'treasure_cangyan_flag', chance: 0.015 },
      { id: 'treasure_fenyu_wheel', chance: 0.015 },
      { id: 'treasure_jiehuo_token', chance: 0.015 },
      { id: 'treasure_xuanwu_core', chance: 0.015 },
      { id: 'treasure_taiyin_mirror', chance: 0.015 },
      { id: 'treasure_guiyuan_bead', chance: 0.015 },
      { id: 'treasure_youluo_lamp', chance: 0.015 },
      { id: 'treasure_shigou_nail', chance: 0.015 },
      { id: 'treasure_shehun_banner', chance: 0.015 },
      { id: 'treasure_shiling_chain', chance: 0.015 },
      { id: 'treasure_duanpo_bell', chance: 0.015 },
      { id: 'treasure_fushen_lu', chance: 0.015 }
    ]
  },
  sabak_boss: {
    id: 'sabak_boss',
    name: '沙巴克守护·玄武',
    level: 55,
    hp: 252000,
    atk: 112,
    def: 54,
    mdef: 54,
    exp: 4200,
    gold: [1050, 1820],
    sabakBoss: true,
    specialBoss: true,
    respawnMs: 1 * 60 * 60 * 1000,
    drops: [
      { id: 'kaitian', chance: 0.02 },
      { id: 'zhentian', chance: 0.02 },
      { id: 'xuantian', chance: 0.02 },
      { id: 'armor_molong', chance: 0.2 },
      { id: 'armor_taishan', chance: 0.08 },
      { id: 'armor_doom', chance: 0.08 },
      { id: 'armor_magic', chance: 0.08 },
      { id: 'wulong', chance: 0.08 },
      { id: 'nujian', chance: 0.08 },
      { id: 'blood_drink', chance: 0.08 },
      { id: 'helm_holy', chance: 0.03 },
      { id: 'helm_mage', chance: 0.03 },
      { id: 'helm_tao', chance: 0.03 },
      { id: 'boots_holy', chance: 0.03 },
      { id: 'boots_mage', chance: 0.03 },
      { id: 'boots_tao', chance: 0.03 },
      { id: 'belt_holy', chance: 0.03 },
      { id: 'belt_mage', chance: 0.03 },
      { id: 'belt_tao', chance: 0.03 },
      { id: 'bracelet_soldier', chance: 0.06 },
      { id: 'bracelet_fashen', chance: 0.06 },
      { id: 'bracelet_tianzun', chance: 0.06 },
      { id: 'armor_thunder', chance: 0.02 },
      { id: 'armor_flame', chance: 0.02 },
      { id: 'armor_glow', chance: 0.02 },
      { id: 'helm_wargod', chance: 0.01 },
      { id: 'helm_sacred', chance: 0.01 },
      { id: 'helm_true', chance: 0.01 },
      { id: 'boots_wargod', chance: 0.01 },
      { id: 'boots_sacred', chance: 0.01 },
      { id: 'boots_true', chance: 0.01 },
      { id: 'belt_wargod', chance: 0.01 },
      { id: 'belt_sacred', chance: 0.01 },
      { id: 'belt_true', chance: 0.01 },
      { id: 'ring_holy', chance: 0.06 },
      { id: 'ring_fashen', chance: 0.06 },
      { id: 'ring_tianzun', chance: 0.06 },
      { id: 'necklace_soldier', chance: 0.06 },
      { id: 'necklace_fashen', chance: 0.06 },
      { id: 'necklace_tianzun', chance: 0.06 },
      { id: 'ring_wargod', chance: 0.006 },
      { id: 'ring_sacred', chance: 0.006 },
      { id: 'ring_true', chance: 0.006 },
      { id: 'necklace_wargod', chance: 0.006 },
      { id: 'necklace_sacred', chance: 0.006 },
      { id: 'necklace_true', chance: 0.006 },
      { id: 'bracelet_wargod', chance: 0.006 },
      { id: 'bracelet_sacred', chance: 0.006 },
      { id: 'bracelet_true', chance: 0.006 },
      { id: 'ring_dodge', chance: 0.02 },
      { id: 'ring_def', chance: 0.02 },
      { id: 'ring_fire', chance: 0.02 },
      { id: 'ring_heal', chance: 0.02 },
      { id: 'ring_magic', chance: 0.02 },
      { id: 'ring_teleport', chance: 0.02 },
      { id: 'ring_protect', chance: 0.02 },
      { id: 'ring_revival', chance: 0.02 },
      { id: 'ring_break', chance: 0.02 },
      { id: 'ring_recall', chance: 0.015 }
    ]
  },
  cultivation_boss_zhuji: {
    id: 'cultivation_boss_zhuji',
    name: '筑基魔君',
    level: 30,
    hp: 8000,
    atk: 120,
    def: 50,
    mdef: 50,
    exp: 3000,
    gold: [600, 1000],
    respawnMs: 30 * 60 * 1000,
    drops: CULTIVATION_BOSS_DROPS.zhuji
  },
  cultivation_boss_lingxu: {
    id: 'cultivation_boss_lingxu',
    name: '灵虚魔君',
    level: 35,
    hp: 10000,
    atk: 135,
    def: 56,
    mdef: 56,
    exp: 3600,
    gold: [700, 1200],
    respawnMs: 30 * 60 * 1000,
    drops: CULTIVATION_BOSS_DROPS.lingxu
  },
  cultivation_boss_hehe: {
    id: 'cultivation_boss_hehe',
    name: '和合魔君',
    level: 40,
    hp: 12000,
    atk: 150,
    def: 62,
    mdef: 62,
    exp: 4200,
    gold: [800, 1400],
    respawnMs: 30 * 60 * 1000,
    drops: CULTIVATION_BOSS_DROPS.hehe
  },
  cultivation_boss_yuanying: {
    id: 'cultivation_boss_yuanying',
    name: '元婴魔君',
    level: 45,
    hp: 15000,
    atk: 165,
    def: 68,
    mdef: 68,
    exp: 4800,
    gold: [900, 1600],
    respawnMs: 30 * 60 * 1000,
    drops: CULTIVATION_BOSS_DROPS.yuanying
  },
  cultivation_boss_kongming: {
    id: 'cultivation_boss_kongming',
    name: '空冥魔君',
    level: 50,
    hp: 18000,
    atk: 180,
    def: 74,
    mdef: 74,
    exp: 5400,
    gold: [1000, 1800],
    respawnMs: 30 * 60 * 1000,
    drops: CULTIVATION_BOSS_DROPS.kongming
  },
  cultivation_boss_lvshuang: {
    id: 'cultivation_boss_lvshuang',
    name: '履霜魔君',
    level: 55,
    hp: 22000,
    atk: 195,
    def: 80,
    mdef: 80,
    exp: 6200,
    gold: [1100, 2000],
    respawnMs: 30 * 60 * 1000,
    drops: CULTIVATION_BOSS_DROPS.lvshuang
  },
  cultivation_boss_dujie: {
    id: 'cultivation_boss_dujie',
    name: '渡劫魔君',
    level: 60,
    hp: 26000,
    atk: 210,
    def: 86,
    mdef: 86,
    exp: 7000,
    gold: [1200, 2200],
    respawnMs: 30 * 60 * 1000,
    drops: CULTIVATION_BOSS_DROPS.dujie
  },
  cultivation_boss_jimie: {
    id: 'cultivation_boss_jimie',
    name: '寂灭魔君',
    level: 65,
    hp: 30000,
    atk: 225,
    def: 92,
    mdef: 92,
    exp: 7800,
    gold: [1300, 2400],
    respawnMs: 30 * 60 * 1000,
    drops: CULTIVATION_BOSS_DROPS.jimie
  },
  cultivation_boss_dacheng: {
    id: 'cultivation_boss_dacheng',
    name: '大乘魔君',
    level: 70,
    hp: 35000,
    atk: 240,
    def: 98,
    mdef: 98,
    exp: 8600,
    gold: [1400, 2600],
    respawnMs: 30 * 60 * 1000,
    drops: CULTIVATION_BOSS_DROPS.dacheng
  },
  cultivation_boss_shangxian: {
    id: 'cultivation_boss_shangxian',
    name: '上仙魔君',
    level: 75,
    hp: 40000,
    atk: 255,
    def: 104,
    mdef: 104,
    exp: 9400,
    gold: [1500, 2800],
    respawnMs: 30 * 60 * 1000,
    drops: CULTIVATION_BOSS_DROPS.shangxian
  },
  cultivation_boss_zhenxian: {
    id: 'cultivation_boss_zhenxian',
    name: '真仙魔君',
    level: 80,
    hp: 46000,
    atk: 270,
    def: 110,
    mdef: 110,
    exp: 10200,
    gold: [1600, 3000],
    respawnMs: 30 * 60 * 1000,
    drops: CULTIVATION_BOSS_DROPS.zhenxian
  },
  cultivation_boss_tianxian: {
    id: 'cultivation_boss_tianxian',
    name: '天仙魔君',
    level: 85,
    hp: 52000,
    atk: 285,
    def: 116,
    mdef: 116,
    exp: 11000,
    gold: [1700, 3200],
    respawnMs: 30 * 60 * 1000,
    drops: CULTIVATION_BOSS_DROPS.tianxian
  },

  cultivation_zhuji_1: {
    id: 'cultivation_zhuji_1',
    name: '筑基妖灵',
    level: 31,
    hp: 1320,
    atk: 84,
    def: 42,
    mdef: 42,
    exp: 4500,
    gold: [1000, 1600],
    drops: CULTIVATION_DROPS.zhuji
  },
  cultivation_zhuji_2: {
    id: 'cultivation_zhuji_2',
    name: '筑基妖兵',
    level: 32,
    hp: 1440,
    atk: 88,
    def: 44,
    mdef: 44,
    exp: 4500,
    gold: [1000, 1600],
    drops: CULTIVATION_DROPS.zhuji
  },
  cultivation_zhuji_3: {
    id: 'cultivation_zhuji_3',
    name: '筑基邪影',
    level: 33,
    hp: 1560,
    atk: 92,
    def: 46,
    mdef: 46,
    exp: 4500,
    gold: [1000, 1600],
    drops: CULTIVATION_DROPS.zhuji
  },
  cultivation_zhuji_4: {
    id: 'cultivation_zhuji_4',
    name: '筑基魔卫',
    level: 34,
    hp: 1680,
    atk: 96,
    def: 48,
    mdef: 48,
    exp: 4500,
    gold: [1000, 1600],
    drops: CULTIVATION_DROPS.zhuji
  },
  cultivation_zhuji_5: {
    id: 'cultivation_zhuji_5',
    name: '筑基狂徒',
    level: 35,
    hp: 1800,
    atk: 100,
    def: 50,
    mdef: 50,
    exp: 4500,
    gold: [1000, 1600],
    drops: CULTIVATION_DROPS.zhuji
  },
  cultivation_lingxu_1: {
    id: 'cultivation_lingxu_1',
    name: '灵虚妖灵',
    level: 34,
    hp: 1720,
    atk: 96,
    def: 50,
    mdef: 50,
    exp: 9000,
    gold: [2000, 3200],
    drops: CULTIVATION_DROPS.lingxu
  },
  cultivation_lingxu_2: {
    id: 'cultivation_lingxu_2',
    name: '灵虚妖兵',
    level: 35,
    hp: 1840,
    atk: 100,
    def: 52,
    mdef: 52,
    exp: 9000,
    gold: [2000, 3200],
    drops: CULTIVATION_DROPS.lingxu
  },
  cultivation_lingxu_3: {
    id: 'cultivation_lingxu_3',
    name: '灵虚邪影',
    level: 36,
    hp: 1960,
    atk: 104,
    def: 54,
    mdef: 54,
    exp: 9000,
    gold: [2000, 3200],
    drops: CULTIVATION_DROPS.lingxu
  },
  cultivation_lingxu_4: {
    id: 'cultivation_lingxu_4',
    name: '灵虚魔卫',
    level: 37,
    hp: 2080,
    atk: 108,
    def: 56,
    mdef: 56,
    exp: 9000,
    gold: [2000, 3200],
    drops: CULTIVATION_DROPS.lingxu
  },
  cultivation_lingxu_5: {
    id: 'cultivation_lingxu_5',
    name: '灵虚狂徒',
    level: 38,
    hp: 2200,
    atk: 112,
    def: 58,
    mdef: 58,
    exp: 9000,
    gold: [2000, 3200],
    drops: CULTIVATION_DROPS.lingxu
  },
  cultivation_hehe_1: {
    id: 'cultivation_hehe_1',
    name: '和合妖灵',
    level: 37,
    hp: 2120,
    atk: 108,
    def: 58,
    mdef: 58,
    exp: 13500,
    gold: [3000, 4800],
    drops: CULTIVATION_DROPS.hehe
  },
  cultivation_hehe_2: {
    id: 'cultivation_hehe_2',
    name: '和合妖兵',
    level: 38,
    hp: 2240,
    atk: 112,
    def: 60,
    mdef: 60,
    exp: 13500,
    gold: [3000, 4800],
    drops: CULTIVATION_DROPS.hehe
  },
  cultivation_hehe_3: {
    id: 'cultivation_hehe_3',
    name: '和合邪影',
    level: 39,
    hp: 2360,
    atk: 116,
    def: 62,
    mdef: 62,
    exp: 13500,
    gold: [3000, 4800],
    drops: CULTIVATION_DROPS.hehe
  },
  cultivation_hehe_4: {
    id: 'cultivation_hehe_4',
    name: '和合魔卫',
    level: 40,
    hp: 2480,
    atk: 120,
    def: 64,
    mdef: 64,
    exp: 13500,
    gold: [3000, 4800],
    drops: CULTIVATION_DROPS.hehe
  },
  cultivation_hehe_5: {
    id: 'cultivation_hehe_5',
    name: '和合狂徒',
    level: 41,
    hp: 2600,
    atk: 124,
    def: 66,
    mdef: 66,
    exp: 13500,
    gold: [3000, 4800],
    drops: CULTIVATION_DROPS.hehe
  },
  cultivation_yuanying_1: {
    id: 'cultivation_yuanying_1',
    name: '元婴妖灵',
    level: 40,
    hp: 2520,
    atk: 120,
    def: 66,
    mdef: 66,
    exp: 18000,
    gold: [4000, 6400],
    drops: CULTIVATION_DROPS.yuanying
  },
  cultivation_yuanying_2: {
    id: 'cultivation_yuanying_2',
    name: '元婴妖兵',
    level: 41,
    hp: 2640,
    atk: 124,
    def: 68,
    mdef: 68,
    exp: 18000,
    gold: [4000, 6400],
    drops: CULTIVATION_DROPS.yuanying
  },
  cultivation_yuanying_3: {
    id: 'cultivation_yuanying_3',
    name: '元婴邪影',
    level: 42,
    hp: 2760,
    atk: 128,
    def: 70,
    mdef: 70,
    exp: 18000,
    gold: [4000, 6400],
    drops: CULTIVATION_DROPS.yuanying
  },
  cultivation_yuanying_4: {
    id: 'cultivation_yuanying_4',
    name: '元婴魔卫',
    level: 43,
    hp: 2880,
    atk: 132,
    def: 72,
    mdef: 72,
    exp: 18000,
    gold: [4000, 6400],
    drops: CULTIVATION_DROPS.yuanying
  },
  cultivation_yuanying_5: {
    id: 'cultivation_yuanying_5',
    name: '元婴狂徒',
    level: 44,
    hp: 3000,
    atk: 136,
    def: 74,
    mdef: 74,
    exp: 18000,
    gold: [4000, 6400],
    drops: CULTIVATION_DROPS.yuanying
  },
  cultivation_kongming_1: {
    id: 'cultivation_kongming_1',
    name: '空冥妖灵',
    level: 43,
    hp: 2920,
    atk: 132,
    def: 74,
    mdef: 74,
    exp: 22500,
    gold: [5000, 8000],
    drops: CULTIVATION_DROPS.kongming
  },
  cultivation_kongming_2: {
    id: 'cultivation_kongming_2',
    name: '空冥妖兵',
    level: 44,
    hp: 3040,
    atk: 136,
    def: 76,
    mdef: 76,
    exp: 22500,
    gold: [5000, 8000],
    drops: CULTIVATION_DROPS.kongming
  },
  cultivation_kongming_3: {
    id: 'cultivation_kongming_3',
    name: '空冥邪影',
    level: 45,
    hp: 3160,
    atk: 140,
    def: 78,
    mdef: 78,
    exp: 22500,
    gold: [5000, 8000],
    drops: CULTIVATION_DROPS.kongming
  },
  cultivation_kongming_4: {
    id: 'cultivation_kongming_4',
    name: '空冥魔卫',
    level: 46,
    hp: 3280,
    atk: 144,
    def: 80,
    mdef: 80,
    exp: 22500,
    gold: [5000, 8000],
    drops: CULTIVATION_DROPS.kongming
  },
  cultivation_kongming_5: {
    id: 'cultivation_kongming_5',
    name: '空冥狂徒',
    level: 47,
    hp: 3400,
    atk: 148,
    def: 82,
    mdef: 82,
    exp: 22500,
    gold: [5000, 8000],
    drops: CULTIVATION_DROPS.kongming
  },
  cultivation_lvshuang_1: {
    id: 'cultivation_lvshuang_1',
    name: '履霜妖灵',
    level: 46,
    hp: 3320,
    atk: 144,
    def: 82,
    mdef: 82,
    exp: 27000,
    gold: [6000, 9600],
    drops: CULTIVATION_DROPS.lvshuang
  },
  cultivation_lvshuang_2: {
    id: 'cultivation_lvshuang_2',
    name: '履霜妖兵',
    level: 47,
    hp: 3440,
    atk: 148,
    def: 84,
    mdef: 84,
    exp: 27000,
    gold: [6000, 9600],
    drops: CULTIVATION_DROPS.lvshuang
  },
  cultivation_lvshuang_3: {
    id: 'cultivation_lvshuang_3',
    name: '履霜邪影',
    level: 48,
    hp: 3560,
    atk: 152,
    def: 86,
    mdef: 86,
    exp: 27000,
    gold: [6000, 9600],
    drops: CULTIVATION_DROPS.lvshuang
  },
  cultivation_lvshuang_4: {
    id: 'cultivation_lvshuang_4',
    name: '履霜魔卫',
    level: 49,
    hp: 3680,
    atk: 156,
    def: 88,
    mdef: 88,
    exp: 27000,
    gold: [6000, 9600],
    drops: CULTIVATION_DROPS.lvshuang
  },
  cultivation_lvshuang_5: {
    id: 'cultivation_lvshuang_5',
    name: '履霜狂徒',
    level: 50,
    hp: 3800,
    atk: 160,
    def: 90,
    mdef: 90,
    exp: 27000,
    gold: [6000, 9600],
    drops: CULTIVATION_DROPS.lvshuang
  },
  cultivation_dujie_1: {
    id: 'cultivation_dujie_1',
    name: '渡劫妖灵',
    level: 49,
    hp: 3720,
    atk: 156,
    def: 90,
    mdef: 90,
    exp: 31500,
    gold: [7000, 11200],
    drops: CULTIVATION_DROPS.dujie
  },
  cultivation_dujie_2: {
    id: 'cultivation_dujie_2',
    name: '渡劫妖兵',
    level: 50,
    hp: 3840,
    atk: 160,
    def: 92,
    mdef: 92,
    exp: 31500,
    gold: [7000, 11200],
    drops: CULTIVATION_DROPS.dujie
  },
  cultivation_dujie_3: {
    id: 'cultivation_dujie_3',
    name: '渡劫邪影',
    level: 51,
    hp: 3960,
    atk: 164,
    def: 94,
    mdef: 94,
    exp: 31500,
    gold: [7000, 11200],
    drops: CULTIVATION_DROPS.dujie
  },
  cultivation_dujie_4: {
    id: 'cultivation_dujie_4',
    name: '渡劫魔卫',
    level: 52,
    hp: 4080,
    atk: 168,
    def: 96,
    mdef: 96,
    exp: 31500,
    gold: [7000, 11200],
    drops: CULTIVATION_DROPS.dujie
  },
  cultivation_dujie_5: {
    id: 'cultivation_dujie_5',
    name: '渡劫狂徒',
    level: 53,
    hp: 4200,
    atk: 172,
    def: 98,
    mdef: 98,
    exp: 31500,
    gold: [7000, 11200],
    drops: CULTIVATION_DROPS.dujie
  },
  cultivation_jimie_1: {
    id: 'cultivation_jimie_1',
    name: '寂灭妖灵',
    level: 52,
    hp: 4120,
    atk: 168,
    def: 98,
    mdef: 98,
    exp: 36000,
    gold: [8000, 12800],
    drops: CULTIVATION_DROPS.jimie
  },
  cultivation_jimie_2: {
    id: 'cultivation_jimie_2',
    name: '寂灭妖兵',
    level: 53,
    hp: 4240,
    atk: 172,
    def: 100,
    mdef: 100,
    exp: 36000,
    gold: [8000, 12800],
    drops: CULTIVATION_DROPS.jimie
  },
  cultivation_jimie_3: {
    id: 'cultivation_jimie_3',
    name: '寂灭邪影',
    level: 54,
    hp: 4360,
    atk: 176,
    def: 102,
    mdef: 102,
    exp: 36000,
    gold: [8000, 12800],
    drops: CULTIVATION_DROPS.jimie
  },
  cultivation_jimie_4: {
    id: 'cultivation_jimie_4',
    name: '寂灭魔卫',
    level: 55,
    hp: 4480,
    atk: 180,
    def: 104,
    mdef: 104,
    exp: 36000,
    gold: [8000, 12800],
    drops: CULTIVATION_DROPS.jimie
  },
  cultivation_jimie_5: {
    id: 'cultivation_jimie_5',
    name: '寂灭狂徒',
    level: 56,
    hp: 4600,
    atk: 184,
    def: 106,
    mdef: 106,
    exp: 36000,
    gold: [8000, 12800],
    drops: CULTIVATION_DROPS.jimie
  },
  cultivation_dacheng_1: {
    id: 'cultivation_dacheng_1',
    name: '大乘妖灵',
    level: 55,
    hp: 4520,
    atk: 180,
    def: 106,
    mdef: 106,
    exp: 40500,
    gold: [9000, 14400],
    drops: CULTIVATION_DROPS.dacheng
  },
  cultivation_dacheng_2: {
    id: 'cultivation_dacheng_2',
    name: '大乘妖兵',
    level: 56,
    hp: 4640,
    atk: 184,
    def: 108,
    mdef: 108,
    exp: 40500,
    gold: [9000, 14400],
    drops: CULTIVATION_DROPS.dacheng
  },
  cultivation_dacheng_3: {
    id: 'cultivation_dacheng_3',
    name: '大乘邪影',
    level: 57,
    hp: 4760,
    atk: 188,
    def: 110,
    mdef: 110,
    exp: 40500,
    gold: [9000, 14400],
    drops: CULTIVATION_DROPS.dacheng
  },
  cultivation_dacheng_4: {
    id: 'cultivation_dacheng_4',
    name: '大乘魔卫',
    level: 58,
    hp: 4880,
    atk: 192,
    def: 112,
    mdef: 112,
    exp: 40500,
    gold: [9000, 14400],
    drops: CULTIVATION_DROPS.dacheng
  },
  cultivation_dacheng_5: {
    id: 'cultivation_dacheng_5',
    name: '大乘狂徒',
    level: 59,
    hp: 5000,
    atk: 196,
    def: 114,
    mdef: 114,
    exp: 40500,
    gold: [9000, 14400],
    drops: CULTIVATION_DROPS.dacheng
  },
  cultivation_shangxian_1: {
    id: 'cultivation_shangxian_1',
    name: '上仙妖灵',
    level: 58,
    hp: 4920,
    atk: 192,
    def: 114,
    mdef: 114,
    exp: 45000,
    gold: [10000, 16000],
    drops: CULTIVATION_DROPS.shangxian
  },
  cultivation_shangxian_2: {
    id: 'cultivation_shangxian_2',
    name: '上仙妖兵',
    level: 59,
    hp: 5040,
    atk: 196,
    def: 116,
    mdef: 116,
    exp: 45000,
    gold: [10000, 16000],
    drops: CULTIVATION_DROPS.shangxian
  },
  cultivation_shangxian_3: {
    id: 'cultivation_shangxian_3',
    name: '上仙邪影',
    level: 60,
    hp: 5160,
    atk: 200,
    def: 118,
    mdef: 118,
    exp: 45000,
    gold: [10000, 16000],
    drops: CULTIVATION_DROPS.shangxian
  },
  cultivation_shangxian_4: {
    id: 'cultivation_shangxian_4',
    name: '上仙魔卫',
    level: 61,
    hp: 5280,
    atk: 204,
    def: 120,
    mdef: 120,
    exp: 45000,
    gold: [10000, 16000],
    drops: CULTIVATION_DROPS.shangxian
  },
  cultivation_shangxian_5: {
    id: 'cultivation_shangxian_5',
    name: '上仙狂徒',
    level: 62,
    hp: 5400,
    atk: 208,
    def: 122,
    mdef: 122,
    exp: 45000,
    gold: [10000, 16000],
    drops: CULTIVATION_DROPS.shangxian
  },
  cultivation_zhenxian_1: {
    id: 'cultivation_zhenxian_1',
    name: '真仙妖灵',
    level: 61,
    hp: 5320,
    atk: 204,
    def: 122,
    mdef: 122,
    exp: 49500,
    gold: [11000, 17600],
    drops: CULTIVATION_DROPS.zhenxian
  },
  cultivation_zhenxian_2: {
    id: 'cultivation_zhenxian_2',
    name: '真仙妖兵',
    level: 62,
    hp: 5440,
    atk: 208,
    def: 124,
    mdef: 124,
    exp: 49500,
    gold: [11000, 17600],
    drops: CULTIVATION_DROPS.zhenxian
  },
  cultivation_zhenxian_3: {
    id: 'cultivation_zhenxian_3',
    name: '真仙邪影',
    level: 63,
    hp: 5560,
    atk: 212,
    def: 126,
    mdef: 126,
    exp: 49500,
    gold: [11000, 17600],
    drops: CULTIVATION_DROPS.zhenxian
  },
  cultivation_zhenxian_4: {
    id: 'cultivation_zhenxian_4',
    name: '真仙魔卫',
    level: 64,
    hp: 5680,
    atk: 216,
    def: 128,
    mdef: 128,
    exp: 49500,
    gold: [11000, 17600],
    drops: CULTIVATION_DROPS.zhenxian
  },
  cultivation_zhenxian_5: {
    id: 'cultivation_zhenxian_5',
    name: '真仙狂徒',
    level: 65,
    hp: 5800,
    atk: 220,
    def: 130,
    mdef: 130,
    exp: 49500,
    gold: [11000, 17600],
    drops: CULTIVATION_DROPS.zhenxian
  },
  cultivation_tianxian_1: {
    id: 'cultivation_tianxian_1',
    name: '天仙妖灵',
    level: 64,
    hp: 5720,
    atk: 216,
    def: 130,
    mdef: 130,
    exp: 54000,
    gold: [12000, 19200],
    drops: CULTIVATION_DROPS.tianxian
  },
  cultivation_tianxian_2: {
    id: 'cultivation_tianxian_2',
    name: '天仙妖兵',
    level: 65,
    hp: 5840,
    atk: 220,
    def: 132,
    mdef: 132,
    exp: 54000,
    gold: [12000, 19200],
    drops: CULTIVATION_DROPS.tianxian
  },
  cultivation_tianxian_3: {
    id: 'cultivation_tianxian_3',
    name: '天仙邪影',
    level: 66,
    hp: 5960,
    atk: 224,
    def: 134,
    mdef: 134,
    exp: 54000,
    gold: [12000, 19200],
    drops: CULTIVATION_DROPS.tianxian
  },
  cultivation_tianxian_4: {
    id: 'cultivation_tianxian_4',
    name: '天仙魔卫',
    level: 67,
    hp: 6080,
    atk: 228,
    def: 136,
    mdef: 136,
    exp: 54000,
    gold: [12000, 19200],
    drops: CULTIVATION_DROPS.tianxian
  },
  cultivation_tianxian_5: {
    id: 'cultivation_tianxian_5',
    name: '天仙狂徒',
    level: 68,
    hp: 6200,
    atk: 232,
    def: 138,
    mdef: 138,
    exp: 54000,
    gold: [12000, 19200],
    drops: CULTIVATION_DROPS.tianxian
  },
  zxft_mob_1: {
    id: 'zxft_mob_1',
    name: '浮图塔灵兵',
    level: 70,
    hp: 7200,
    atk: 248,
    def: 142,
    mdef: 142,
    exp: 62000,
    gold: [13000, 18000],
    drops: []
  },
  zxft_mob_2: {
    id: 'zxft_mob_2',
    name: '浮图塔邪侍',
    level: 71,
    hp: 7400,
    atk: 252,
    def: 144,
    mdef: 144,
    exp: 62000,
    gold: [13000, 18000],
    drops: []
  },
  zxft_mob_3: {
    id: 'zxft_mob_3',
    name: '浮图塔禁卫',
    level: 72,
    hp: 7600,
    atk: 256,
    def: 146,
    mdef: 146,
    exp: 62000,
    gold: [13000, 18000],
    drops: []
  },
  zxft_mob_4: {
    id: 'zxft_mob_4',
    name: '浮图塔妖将',
    level: 73,
    hp: 7800,
    atk: 260,
    def: 148,
    mdef: 148,
    exp: 62000,
    gold: [13000, 18000],
    drops: []
  },
  zxft_mob_5: {
    id: 'zxft_mob_5',
    name: '浮图塔魔将',
    level: 74,
    hp: 8000,
    atk: 264,
    def: 150,
    mdef: 150,
    exp: 62000,
    gold: [13000, 18000],
    drops: []
  },
  zxft_boss: {
    id: 'zxft_boss',
    name: '浮图塔镇层魔君',
    level: 80,
    hp: 18000,
    atk: 360,
    def: 220,
    mdef: 220,
    exp: 160000,
    gold: [30000, 45000],
    drops: []
  },
  mob_summon_skeleton: {
    id: 'mob_summon_skeleton',
    name: '召唤骷髅',
    level: 10,
    hp: 200,
    atk: 20,
    def: 8,
    mdef: 4,
    gold: [0, 0],
    drops: [],
    summoned: true
  },
  mob_summon_beast: {
    id: 'mob_summon_beast',
    name: '召唤神兽',
    level: 12,
    hp: 320,
    atk: 28,
    def: 12,
    mdef: 6,
    gold: [0, 0],
    drops: [],
    summoned: true
  },
  mob_summon_white_tiger: {
    id: 'mob_summon_white_tiger',
    name: '召唤白虎',
    level: 15,
    hp: 480,
    atk: 40,
    def: 16,
    mdef: 8,
    gold: [0, 0],
    drops: [],
    summoned: true
  }
};

const EXTRA_CULTIVATION_TIERS = [
  { slug: 'shengwen', name: '声闻', levelIndex: 12 },
  { slug: 'yuanjue', name: '缘觉', levelIndex: 13 },
  { slug: 'pusa', name: '菩萨', levelIndex: 14 },
  { slug: 'fo', name: '佛', levelIndex: 15 }
];

function cloneMobTemplate(template) {
  return JSON.parse(JSON.stringify(template));
}

function scaleRange(range, factor) {
  if (!Array.isArray(range)) return range;
  return [Math.max(0, Math.floor(Number(range[0] || 0) * factor)), Math.max(0, Math.floor(Number(range[1] || 0) * factor))];
}

function extendCultivationMobs() {
  const baseBoss = MOB_TEMPLATES.cultivation_boss_tianxian;
  if (!baseBoss) return;
  const baseFields = [1, 2, 3, 4, 5].map((i) => MOB_TEMPLATES[`cultivation_tianxian_${i}`]).filter(Boolean);
  EXTRA_CULTIVATION_TIERS.forEach((tier, idx) => {
    const fieldFactor = 1 + (idx + 1) * 0.18;
    const bossFactor = 1 + (idx + 1) * 0.22;
    baseFields.forEach((baseField, i) => {
      const next = cloneMobTemplate(baseField);
      next.id = `cultivation_${tier.slug}_${i + 1}`;
      next.name = String(baseField.name || '').replace(/^天仙/, tier.name) || `${tier.name}妖灵`;
      next.level = Math.max(1, Math.floor(Number(baseField.level || 1) + (idx + 1) * 3));
      next.hp = Math.max(1, Math.floor(Number(baseField.hp || 1) * fieldFactor));
      next.atk = Math.max(1, Math.floor(Number(baseField.atk || 1) * (1 + (idx + 1) * 0.12)));
      next.def = Math.max(0, Math.floor(Number(baseField.def || 0) * (1 + (idx + 1) * 0.1)));
      next.mdef = Math.max(0, Math.floor(Number(baseField.mdef || 0) * (1 + (idx + 1) * 0.1)));
      next.exp = Math.max(1, Math.floor(Number(baseField.exp || 1) * fieldFactor));
      next.gold = scaleRange(baseField.gold, fieldFactor);
      next.drops = CULTIVATION_DROPS[tier.slug] || baseField.drops || [];
      MOB_TEMPLATES[next.id] = next;
    });

    const boss = cloneMobTemplate(baseBoss);
    boss.id = `cultivation_boss_${tier.slug}`;
    boss.name = `${tier.name}魔君`;
    boss.level = Math.max(1, Math.floor(Number(baseBoss.level || 1) + (idx + 1) * 5));
    boss.hp = Math.max(1, Math.floor(Number(baseBoss.hp || 1) * bossFactor));
    boss.atk = Math.max(1, Math.floor(Number(baseBoss.atk || 1) * (1 + (idx + 1) * 0.15)));
    boss.def = Math.max(0, Math.floor(Number(baseBoss.def || 0) * (1 + (idx + 1) * 0.12)));
    boss.mdef = Math.max(0, Math.floor(Number(baseBoss.mdef || 0) * (1 + (idx + 1) * 0.12)));
    boss.exp = Math.max(1, Math.floor(Number(baseBoss.exp || 1) * bossFactor));
    boss.gold = scaleRange(baseBoss.gold, bossFactor);
    boss.drops = CULTIVATION_BOSS_DROPS[tier.slug] || baseBoss.drops || [];
    MOB_TEMPLATES[boss.id] = boss;
  });
}

extendCultivationMobs();

function nerfCultivationFieldBaseExp() {
  Object.keys(MOB_TEMPLATES).forEach((id) => {
    if (!String(id).startsWith('cultivation_')) return;
    if (String(id).startsWith('cultivation_boss_')) return;
    const mob = MOB_TEMPLATES[id];
    if (!mob) return;
    mob.exp = Math.max(1, Math.floor(Number(mob.exp || 0) * 0.5));
  });
}

nerfCultivationFieldBaseExp();


