services:
  text-legend:
    image: ghcr.io/e5sub/text-legend:latest
    container_name: text-legend
    hostname: text-legend
    restart: unless-stopped
    network_mode: host
    environment:
      - DB_CLIENT=mysql
      - DB_HOST=你的数据库地址
      - DB_USER=你的数据库用户名
      - DB_PASSWORD=你的数据库密码
      - DB_NAME=你的数据库名
      - DB_POOL_MAX=10 #数据库连接池最大连接数，默认为10，根据实际情况调整
      - TZ=Asia/Shanghai
      - PORT=3000
      - SESSION_TTL_MIN=0 
      - ADMIN_BOOTSTRAP_SECRET=GM账号 #GM账号账号
      - ADMIN_BOOTSTRAP_USER=GM密码 #GM账号密码
      - ADMIN_PATH=admin  #默认后台地址admin，可以修改为其他路径
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    volumes:
      - ./data:/app/data